#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FloPotatoes.Android.Resource", IsApplication=true)]

namespace FloPotatoes.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::FloPotatoes.Android.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::FloPotatoes.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int Black = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int Blue = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Orange = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Tomatoes = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int White = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int Yellow = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chevron_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_critics_fresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_error = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_fresh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_loading = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_pop_corn = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_rotten = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int actorView = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int castListView = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int certifiedView = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int criticsReviewListView = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int dateView = 2131165204;
			
			// aapt resource value: 0x7f07000c
			public const int directorView = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int genreView = 2131165198;
			
			// aapt resource value: 0x7f07001a
			public const int listView = 2131165210;
			
			// aapt resource value: 0x7f070002
			public const int movieDesc = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int mpaaView = 2131165193;
			
			// aapt resource value: 0x7f070016
			public const int nameView = 2131165206;
			
			// aapt resource value: 0x7f070003
			public const int pictureView = 2131165187;
			
			// aapt resource value: 0x7f070018
			public const int quoteView = 2131165208;
			
			// aapt resource value: 0x7f070005
			public const int ratingPercentView = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int ratingPicView = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int runningTimeView = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int runtime = 2131165194;
			
			// aapt resource value: 0x7f070013
			public const int scoreView = 2131165203;
			
			// aapt resource value: 0x7f07001b
			public const int separatorView = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int sourceView = 2131165207;
			
			// aapt resource value: 0x7f07001c
			public const int splashscreen = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int swipe_container = 2131165209;
			
			// aapt resource value: 0x7f07000b
			public const int synopsisView = 2131165195;
			
			// aapt resource value: 0x7f070015
			public const int textView = 2131165205;
			
			// aapt resource value: 0x7f070008
			public const int theaterRealseView = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int theaterReleaseView = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int titleBar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int titleView = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int userRatingPercentView = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Movie = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Adapter_Home_Movie = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Adapter_Movie_Cast = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Adapter_Movie_Reviews = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Separator = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Splashscreen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int Action_Settings = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Activity_Home = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Activity_Movie = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int App_Name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int Critics_Liked_It = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int Director = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int Genre = 2130968594;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Hello_World = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int List_Box_Office = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int List_Opening = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int List_Theater = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int Rated = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int Running_Time = 2130968596;
			
			// aapt resource value: 0x7f04000f
			public const int Synopsis = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int Theater_Release = 2130968595;
			
			// aapt resource value: 0x7f04000d
			public const int Title_Cast = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int Title_Critics_Review = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int Title_Movie_Info = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int Users_Liked_It = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
